### ISSUE TITLE
Create AsciiDoc WG Website

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/asciidoc.eclipse.org#1]
I made the initial commit for this project. I did my best to include variations of the different things you can do with our template.

For example, I added a menu, sidebar menu, and dropdown menus in https://github.com/EclipseFdn/asciidoc.eclipse.org/blob/main/config.toml

The content of the main branch is available via https://eclipsefdn-asciidoc.netlify.app/. However, the plan would be to host the site on EF infra under asciidoc.eclipse.org.

GETTING STARTED:
https://github.com/EclipseFdn/asciidoc.eclipse.org#getting-started

Hugo Documentation:
https://gohugo.io/documentation

Theme Documentation:
https://eclipsefdn-hugo-solstice-theme.netlify.app/

Eclipse Foundation Hosted Services Privacy and Acceptable Usage Policy:
https://blogs.eclipse.org/post/christopher-guindon/eclipse-foundation-hosted-services-privacy-and-acceptable-usage-policy

@rkratky @ahus1 Please let us know if you have any questions via this issue!

**Comment by chrisguindon** [comment]
@EclipseFdn/asciidoc-eclipse-org,

Do you have any questions or blockers? Please let us know if we can help!

**Comment by rkratky** [comment]
@chrisguindon, I haven't had the time to take a look yet. I hope to explore tomorrow or over the weekend.

**Comment by ahus1** [comment]
Getting started worked ok, now we're about to add content. Closing this for now.
